/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as StudentRouteImport } from './routes/student'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAssignmentsRouteImport } from './routes/admin.assignments'
import { Route as AdminCareerRouteImport } from './routes/admin.career'
import { Route as AdminMaterialsRouteImport } from './routes/admin.materials'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as ParentIndexRouteImport } from './routes/parent.index'
import { Route as ParentProfileRouteImport } from './routes/parent.profile'
import { Route as ParentProgressRouteImport } from './routes/parent.progress'
import { Route as ParentReportsRouteImport } from './routes/parent.reports'
import { Route as ParentSettingsRouteImport } from './routes/parent.settings'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as StudentCareerRouteImport } from './routes/student.career'
import { Route as StudentInsightsRouteImport } from './routes/student.insights'
import { Route as StudentLearningRouteImport } from './routes/student.learning'
import { Route as StudentOnboardingRouteImport } from './routes/student.onboarding'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentProgressRouteImport } from './routes/student.progress'
import { Route as StudentReportsRouteImport } from './routes/student.reports'
import { Route as StudentSettingsRouteImport } from './routes/student.settings'
import { Route as StudentStudyPlanRouteImport } from './routes/student.study-plan'
import { Route as StudentTutorRouteImport } from './routes/student.tutor'
import { Route as StudentAssignmentsIndexRouteImport } from './routes/student.assignments.index'
import { Route as StudentAssignmentsAssignmentIdRouteImport } from './routes/student.assignments.$assignmentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssignmentsRoute = AdminAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCareerRoute = AdminCareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMaterialsRoute = AdminMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const ParentIndexRoute = ParentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ParentRoute,
} as any)
const ParentProfileRoute = ParentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ParentRoute,
} as any)
const ParentProgressRoute = ParentProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => ParentRoute,
} as any)
const ParentReportsRoute = ParentReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ParentRoute,
} as any)
const ParentSettingsRoute = ParentSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ParentRoute,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCareerRoute = StudentCareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => StudentRoute,
} as any)
const StudentInsightsRoute = StudentInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => StudentRoute,
} as any)
const StudentLearningRoute = StudentLearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => StudentRoute,
} as any)
const StudentOnboardingRoute = StudentOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProgressRoute = StudentProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => StudentRoute,
} as any)
const StudentReportsRoute = StudentReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => StudentRoute,
} as any)
const StudentSettingsRoute = StudentSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => StudentRoute,
} as any)
const StudentStudyPlanRoute = StudentStudyPlanRouteImport.update({
  id: '/study-plan',
  path: '/study-plan',
  getParentRoute: () => StudentRoute,
} as any)
const StudentTutorRoute = StudentTutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAssignmentsIndexRoute = StudentAssignmentsIndexRouteImport.update({
  id: '/assignments/',
  path: '/assignments/',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAssignmentsAssignmentIdRoute =
  StudentAssignmentsAssignmentIdRouteImport.update({
    id: '/assignments/$assignmentId',
    path: '/assignments/$assignmentId',
    getParentRoute: () => StudentRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/parent': typeof ParentRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/admin/assignments': typeof AdminAssignmentsRoute
  '/admin/career': typeof AdminCareerRoute
  '/admin/materials': typeof AdminMaterialsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/parent/profile': typeof ParentProfileRoute
  '/parent/progress': typeof ParentProgressRoute
  '/parent/reports': typeof ParentReportsRoute
  '/parent/settings': typeof ParentSettingsRoute
  '/student/career': typeof StudentCareerRoute
  '/student/insights': typeof StudentInsightsRoute
  '/student/learning': typeof StudentLearningRoute
  '/student/onboarding': typeof StudentOnboardingRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/progress': typeof StudentProgressRoute
  '/student/reports': typeof StudentReportsRoute
  '/student/settings': typeof StudentSettingsRoute
  '/student/study-plan': typeof StudentStudyPlanRoute
  '/student/tutor': typeof StudentTutorRoute
  '/admin/': typeof AdminIndexRoute
  '/parent/': typeof ParentIndexRoute
  '/student/': typeof StudentIndexRoute
  '/student/assignments/$assignmentId': typeof StudentAssignmentsAssignmentIdRoute
  '/student/assignments/': typeof StudentAssignmentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/admin/assignments': typeof AdminAssignmentsRoute
  '/admin/career': typeof AdminCareerRoute
  '/admin/materials': typeof AdminMaterialsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/parent/profile': typeof ParentProfileRoute
  '/parent/progress': typeof ParentProgressRoute
  '/parent/reports': typeof ParentReportsRoute
  '/parent/settings': typeof ParentSettingsRoute
  '/student/career': typeof StudentCareerRoute
  '/student/insights': typeof StudentInsightsRoute
  '/student/learning': typeof StudentLearningRoute
  '/student/onboarding': typeof StudentOnboardingRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/progress': typeof StudentProgressRoute
  '/student/reports': typeof StudentReportsRoute
  '/student/settings': typeof StudentSettingsRoute
  '/student/study-plan': typeof StudentStudyPlanRoute
  '/student/tutor': typeof StudentTutorRoute
  '/admin': typeof AdminIndexRoute
  '/parent': typeof ParentIndexRoute
  '/student': typeof StudentIndexRoute
  '/student/assignments/$assignmentId': typeof StudentAssignmentsAssignmentIdRoute
  '/student/assignments': typeof StudentAssignmentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/parent': typeof ParentRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/admin/assignments': typeof AdminAssignmentsRoute
  '/admin/career': typeof AdminCareerRoute
  '/admin/materials': typeof AdminMaterialsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/parent/profile': typeof ParentProfileRoute
  '/parent/progress': typeof ParentProgressRoute
  '/parent/reports': typeof ParentReportsRoute
  '/parent/settings': typeof ParentSettingsRoute
  '/student/career': typeof StudentCareerRoute
  '/student/insights': typeof StudentInsightsRoute
  '/student/learning': typeof StudentLearningRoute
  '/student/onboarding': typeof StudentOnboardingRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/progress': typeof StudentProgressRoute
  '/student/reports': typeof StudentReportsRoute
  '/student/settings': typeof StudentSettingsRoute
  '/student/study-plan': typeof StudentStudyPlanRoute
  '/student/tutor': typeof StudentTutorRoute
  '/admin/': typeof AdminIndexRoute
  '/parent/': typeof ParentIndexRoute
  '/student/': typeof StudentIndexRoute
  '/student/assignments/$assignmentId': typeof StudentAssignmentsAssignmentIdRoute
  '/student/assignments/': typeof StudentAssignmentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/onboarding'
    | '/parent'
    | '/student'
    | '/admin/assignments'
    | '/admin/career'
    | '/admin/materials'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/students'
    | '/parent/profile'
    | '/parent/progress'
    | '/parent/reports'
    | '/parent/settings'
    | '/student/career'
    | '/student/insights'
    | '/student/learning'
    | '/student/onboarding'
    | '/student/profile'
    | '/student/progress'
    | '/student/reports'
    | '/student/settings'
    | '/student/study-plan'
    | '/student/tutor'
    | '/admin/'
    | '/parent/'
    | '/student/'
    | '/student/assignments/$assignmentId'
    | '/student/assignments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/admin/assignments'
    | '/admin/career'
    | '/admin/materials'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/students'
    | '/parent/profile'
    | '/parent/progress'
    | '/parent/reports'
    | '/parent/settings'
    | '/student/career'
    | '/student/insights'
    | '/student/learning'
    | '/student/onboarding'
    | '/student/profile'
    | '/student/progress'
    | '/student/reports'
    | '/student/settings'
    | '/student/study-plan'
    | '/student/tutor'
    | '/admin'
    | '/parent'
    | '/student'
    | '/student/assignments/$assignmentId'
    | '/student/assignments'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/onboarding'
    | '/parent'
    | '/student'
    | '/admin/assignments'
    | '/admin/career'
    | '/admin/materials'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/students'
    | '/parent/profile'
    | '/parent/progress'
    | '/parent/reports'
    | '/parent/settings'
    | '/student/career'
    | '/student/insights'
    | '/student/learning'
    | '/student/onboarding'
    | '/student/profile'
    | '/student/progress'
    | '/student/reports'
    | '/student/settings'
    | '/student/study-plan'
    | '/student/tutor'
    | '/admin/'
    | '/parent/'
    | '/student/'
    | '/student/assignments/$assignmentId'
    | '/student/assignments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ParentRoute: typeof ParentRouteWithChildren
  StudentRoute: typeof StudentRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assignments': {
      id: '/admin/assignments'
      path: '/assignments'
      fullPath: '/admin/assignments'
      preLoaderRoute: typeof AdminAssignmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/career': {
      id: '/admin/career'
      path: '/career'
      fullPath: '/admin/career'
      preLoaderRoute: typeof AdminCareerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/materials': {
      id: '/admin/materials'
      path: '/materials'
      fullPath: '/admin/materials'
      preLoaderRoute: typeof AdminMaterialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/parent/': {
      id: '/parent/'
      path: '/'
      fullPath: '/parent/'
      preLoaderRoute: typeof ParentIndexRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/profile': {
      id: '/parent/profile'
      path: '/profile'
      fullPath: '/parent/profile'
      preLoaderRoute: typeof ParentProfileRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/progress': {
      id: '/parent/progress'
      path: '/progress'
      fullPath: '/parent/progress'
      preLoaderRoute: typeof ParentProgressRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/reports': {
      id: '/parent/reports'
      path: '/reports'
      fullPath: '/parent/reports'
      preLoaderRoute: typeof ParentReportsRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/settings': {
      id: '/parent/settings'
      path: '/settings'
      fullPath: '/parent/settings'
      preLoaderRoute: typeof ParentSettingsRouteImport
      parentRoute: typeof ParentRoute
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/career': {
      id: '/student/career'
      path: '/career'
      fullPath: '/student/career'
      preLoaderRoute: typeof StudentCareerRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/insights': {
      id: '/student/insights'
      path: '/insights'
      fullPath: '/student/insights'
      preLoaderRoute: typeof StudentInsightsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/learning': {
      id: '/student/learning'
      path: '/learning'
      fullPath: '/student/learning'
      preLoaderRoute: typeof StudentLearningRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/onboarding': {
      id: '/student/onboarding'
      path: '/onboarding'
      fullPath: '/student/onboarding'
      preLoaderRoute: typeof StudentOnboardingRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/progress': {
      id: '/student/progress'
      path: '/progress'
      fullPath: '/student/progress'
      preLoaderRoute: typeof StudentProgressRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/reports': {
      id: '/student/reports'
      path: '/reports'
      fullPath: '/student/reports'
      preLoaderRoute: typeof StudentReportsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/settings': {
      id: '/student/settings'
      path: '/settings'
      fullPath: '/student/settings'
      preLoaderRoute: typeof StudentSettingsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/study-plan': {
      id: '/student/study-plan'
      path: '/study-plan'
      fullPath: '/student/study-plan'
      preLoaderRoute: typeof StudentStudyPlanRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/tutor': {
      id: '/student/tutor'
      path: '/tutor'
      fullPath: '/student/tutor'
      preLoaderRoute: typeof StudentTutorRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/assignments/': {
      id: '/student/assignments/'
      path: '/assignments'
      fullPath: '/student/assignments/'
      preLoaderRoute: typeof StudentAssignmentsIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/assignments/$assignmentId': {
      id: '/student/assignments/$assignmentId'
      path: '/assignments/$assignmentId'
      fullPath: '/student/assignments/$assignmentId'
      preLoaderRoute: typeof StudentAssignmentsAssignmentIdRouteImport
      parentRoute: typeof StudentRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAssignmentsRoute: typeof AdminAssignmentsRoute
  AdminCareerRoute: typeof AdminCareerRoute
  AdminMaterialsRoute: typeof AdminMaterialsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAssignmentsRoute: AdminAssignmentsRoute,
  AdminCareerRoute: AdminCareerRoute,
  AdminMaterialsRoute: AdminMaterialsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ParentRouteChildren {
  ParentProfileRoute: typeof ParentProfileRoute
  ParentProgressRoute: typeof ParentProgressRoute
  ParentReportsRoute: typeof ParentReportsRoute
  ParentSettingsRoute: typeof ParentSettingsRoute
  ParentIndexRoute: typeof ParentIndexRoute
}

const ParentRouteChildren: ParentRouteChildren = {
  ParentProfileRoute: ParentProfileRoute,
  ParentProgressRoute: ParentProgressRoute,
  ParentReportsRoute: ParentReportsRoute,
  ParentSettingsRoute: ParentSettingsRoute,
  ParentIndexRoute: ParentIndexRoute,
}

const ParentRouteWithChildren =
  ParentRoute._addFileChildren(ParentRouteChildren)

interface StudentRouteChildren {
  StudentCareerRoute: typeof StudentCareerRoute
  StudentInsightsRoute: typeof StudentInsightsRoute
  StudentLearningRoute: typeof StudentLearningRoute
  StudentOnboardingRoute: typeof StudentOnboardingRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentProgressRoute: typeof StudentProgressRoute
  StudentReportsRoute: typeof StudentReportsRoute
  StudentSettingsRoute: typeof StudentSettingsRoute
  StudentStudyPlanRoute: typeof StudentStudyPlanRoute
  StudentTutorRoute: typeof StudentTutorRoute
  StudentIndexRoute: typeof StudentIndexRoute
  StudentAssignmentsAssignmentIdRoute: typeof StudentAssignmentsAssignmentIdRoute
  StudentAssignmentsIndexRoute: typeof StudentAssignmentsIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentCareerRoute: StudentCareerRoute,
  StudentInsightsRoute: StudentInsightsRoute,
  StudentLearningRoute: StudentLearningRoute,
  StudentOnboardingRoute: StudentOnboardingRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentProgressRoute: StudentProgressRoute,
  StudentReportsRoute: StudentReportsRoute,
  StudentSettingsRoute: StudentSettingsRoute,
  StudentStudyPlanRoute: StudentStudyPlanRoute,
  StudentTutorRoute: StudentTutorRoute,
  StudentIndexRoute: StudentIndexRoute,
  StudentAssignmentsAssignmentIdRoute: StudentAssignmentsAssignmentIdRoute,
  StudentAssignmentsIndexRoute: StudentAssignmentsIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ParentRoute: ParentRouteWithChildren,
  StudentRoute: StudentRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
